/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTC5 (number 77), J1[11]/PTC5_T2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_RUN_LED_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_RUN_LED_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_RUN_LED_GPIO_PORT kGPIO_PORTC    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_RUN_LED_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_RUN_LED_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_RUN_LED_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_RUN_LED_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTH1 (number 18), J5[7]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SYS_FAULT_LED_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_SYS_FAULT_LED_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_SYS_FAULT_LED_GPIO_PORT kGPIO_PORTH    /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_SYS_FAULT_LED_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SYS_FAULT_LED_PORT PORTH               /*!<@brief PORT peripheral base pointer */
#define BOARD_SYS_FAULT_LED_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_SYS_FAULT_LED_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTH0 (number 19), J2[4]/PTH0_D9_PWM0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SYS_ALARM_LED_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_SYS_ALARM_LED_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_SYS_ALARM_LED_GPIO_PORT kGPIO_PORTH    /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_SYS_ALARM_LED_GPIO_PIN_MASK (1U << 24U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SYS_ALARM_LED_PORT PORTH               /*!<@brief PORT peripheral base pointer */
#define BOARD_SYS_ALARM_LED_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_SYS_ALARM_LED_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTE6 (number 20), J1[13]/PTE6_LED2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SYS_NORMAL_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_SYS_NORMAL_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_SYS_NORMAL_GPIO_PORT kGPIO_PORTE    /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_SYS_NORMAL_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SYS_NORMAL_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_SYS_NORMAL_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_SYS_NORMAL_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_gpio_led(void);

/*! @name PORTI1 (number 16), J5[12]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_RS485_UART_TX_PORT PORTI               /*!<@brief PORT peripheral base pointer */
#define BOARD_RS485_UART_TX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_RS485_UART_TX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTI0 (number 17), J5[8]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_RS485_UART_RX_PORT PORTI               /*!<@brief PORT peripheral base pointer */
#define BOARD_RS485_UART_RX_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_RS485_UART_RX_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTE3 (number 67), J4[7]/PTE3_SPI0_SS
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_RS485_DIR_RS485_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_RS485_DIR_RS485_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_RS485_DIR_RS485_GPIO_PORT kGPIO_PORTE    /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_RS485_DIR_RS485_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_RS485_DIR_RS485_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_RS485_DIR_RS485_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_RS485_DIR_RS485_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_rs485(void);

/*! @name PORTG4 (number 53), J5[2]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_FLASH_SPI_SPI1_CLK_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_FLASH_SPI_SPI1_CLK_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_FLASH_SPI_SPI1_CLK_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTG5 (number 52), D4[1]/PTG5_RED
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_FLASH_SPI_SPI1_MOSI_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_FLASH_SPI_SPI1_MOSI_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_FLASH_SPI_SPI1_MOSI_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTG6 (number 51), D4[4]/PTG6_GREEN
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_FLASH_SPI_SPI1_MISO_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_FLASH_SPI_SPI1_MISO_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_FLASH_SPI_SPI1_MISO_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTI3 (number 65), J5[16]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_FLASH_SPI_SPI1_CS_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_FLASH_SPI_SPI1_CS_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_FLASH_SPI_SPI1_CS_GPIO_PORT kGPIO_PORTI    /*!<@brief PORTC GPIO port: PORTC */
#define BOARD_FLASH_SPI_SPI1_CS_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_FLASH_SPI_SPI1_CS_PORT PORTI               /*!<@brief PORT peripheral base pointer */
#define BOARD_FLASH_SPI_SPI1_CS_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_FLASH_SPI_SPI1_CS_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTA0 (number 62), J2[2]/PTA0_D8_T0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_FLASH_SPI_SPI1_WP_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_FLASH_SPI_SPI1_WP_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_FLASH_SPI_SPI1_WP_GPIO_PORT kGPIO_PORTA    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_FLASH_SPI_SPI1_WP_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_FLASH_SPI_SPI1_WP_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_FLASH_SPI_SPI1_WP_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_FLASH_SPI_SPI1_WP_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTA1 (number 61), J1[10]/PTA1_D4_T1/PTA1_IRRX
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_FLASH_SPI_SPI1_HOLD_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_FLASH_SPI_SPI1_HOLD_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_FLASH_SPI_SPI1_HOLD_GPIO_PORT kGPIO_PORTA    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_FLASH_SPI_SPI1_HOLD_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_FLASH_SPI_SPI1_HOLD_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_FLASH_SPI_SPI1_HOLD_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_FLASH_SPI_SPI1_HOLD_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_flash_spi(void);

/*! @name PORTE0 (number 76), J4[1]/PTE0_SPI0_SCK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_I2C_I2C_SDA_RTC_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_I2C_I2C_SDA_RTC_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_I2C_I2C_SDA_RTC_GPIO_PORT kGPIO_PORTE    /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_I2C_I2C_SDA_RTC_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_I2C_I2C_SDA_RTC_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_I2C_I2C_SDA_RTC_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_I2C_I2C_SDA_RTC_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTE1 (number 75), J4[3]/PTE1_SPI0_MOSI
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_I2C_I2C_SCL_RTC_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_I2C_I2C_SCL_RTC_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_I2C_I2C_SCL_RTC_GPIO_PORT kGPIO_PORTE    /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_I2C_I2C_SCL_RTC_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_I2C_I2C_SCL_RTC_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_I2C_I2C_SCL_RTC_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_I2C_I2C_SCL_RTC_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTA2 (number 60), J2[18]/PTA2_ACCEL_SDA
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_I2C_I2C_SDA_HUMI_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_I2C_I2C_SDA_HUMI_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_I2C_I2C_SDA_HUMI_GPIO_PORT kGPIO_PORTA    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_I2C_I2C_SDA_HUMI_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_I2C_I2C_SDA_HUMI_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_I2C_I2C_SDA_HUMI_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_I2C_I2C_SDA_HUMI_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTA3 (number 59), J2[20]/PTA3_ACCEL_SCL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_I2C_I2C_SCL_HUMI_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_I2C_I2C_SCL_HUMI_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_I2C_I2C_SCL_HUMI_GPIO_PORT kGPIO_PORTA    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_I2C_I2C_SCL_HUMI_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_I2C_I2C_SCL_HUMI_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_I2C_I2C_SCL_HUMI_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_I2C_I2C_SCL_HUMI_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_i2c(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
